name: Cleanup
description: Cleanup branches after Pull Request is closed
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  head-ref:
    default: ${{ github.head_ref }}
    description: The head branch to delete
    required: false
  pull-request-url:
    description: The Pull Request URL
    required: true
runs:
  using: composite
  steps:
    - id: stack
      uses: shikanime-studio/actions/stack@v9
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - if: ${{ steps.stack.outputs.method == 'github-pull-request' }}
      run: GH_TOKEN="${{ inputs.github-token }}" gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/${{ inputs.head-ref }}" || true
      shell: bash
    - if: ${{ steps.stack.outputs.method == 'ghstack' }}
      run: |
        export GH_TOKEN='${{ inputs.github-token }}'
        HEAD_REF='${{ inputs.head-ref }}'
        REPO='${{ github.repository }}'

        for role in base head orig; do
          gh api -X DELETE "repos/$REPO/git/refs/heads/${HEAD_REF%/head}/$role" || true
        done
      shell: bash
