name: Cleanup
description: Cleanup branches after Pull Request is closed
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  head-ref:
    default: ${{ github.head_ref }}
    description: The head branch to delete
    required: false
  pull-request-url:
    description: The Pull Request URL
    required: true
runs:
  using: composite
  steps:
    - id: checkout
      uses: shikanime-studio/actions/checkout@v9
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-url: ${{ inputs.pull-request-url }}
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        HEAD_REF: ${{ inputs.head-ref }}
      if: ${{ steps.checkout.outputs.method == 'github-pull-request' }}
      run: git push origin --delete "$HEAD_REF" || true
      shell: bash
    - env:
        GH_TOKEN: ${{ inputs.github-token }}
        HEAD_REF: ${{ inputs.head-ref }}
      if: ${{ steps.checkout.outputs.method == 'ghstack' }}
      run: |
        PREFIX="$(printf '%s' "$HEAD_REF" | sed 's#/head$##')"

        for role in base head orig; do
          git push origin --delete "$PREFIX/$role" || true
        done
      shell: bash
