name: Run
description: Trigger a workflow dispatch
inputs:
  github-token:
    default: ${{ github.token }}
    description: The GitHub Token
    required: false
  ref:
    default: ${{ github.ref }}
    description: Git ref to run the workflow on
    required: false
  workflow:
    description: Workflow name or path to run (must support workflow_dispatch)
    required: true
runs:
  using: composite
  steps:
    - run: |
        GH_TOKEN="${{ inputs.github-token }}" gh workflow run "${{ inputs.workflow }}" \
          --ref "${{ inputs.ref }}" \
          --repo "${{ github.repository }}"
      shell: bash
