jobs:
  cleanup:
    runs-on: ubuntu-slim
    steps:
      - continue-on-error: true
        id: createGithubAppToken
        uses: actions/create-github-app-token@v3.1.1
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          permission-contents: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/cleanup@v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
name: Cleanup
'on':
  pull_request:
    types:
      - closed
permissions:
  contents: write
